-- COMANDOS DLL ESTRUTURA DO BANCO DE DADOS --
CREATE DATABASE REGISTRO;


CREATE TABLE REGISTRO.PESSOA(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255)
);